[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SwarmSwIM"
version = "0.4.0"
description = "Simulator for underwater swarm robotics"
readme = "README.md"
authors = [
  { name = "Saverio Iacoponi", email = "saverio.iacoponi@ku.ac.ae" }
]
requires-python = ">=3.8"
dependencies = [
  "numpy",
  "matplotlib",
  "fastapi",
  "uvicorn",
  "opencv-python",
  "pyqtgraph>=0.13",
  "PyQt5",
  "openpyxl",
  "imageio[ffmpeg]>=2.31"
]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
SwarmSwIM = ["*.xml"]
