[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SwarmSwIM"
version = "0.4.0"
description = "Simulator for underwater swarm robotics"
readme = "README.md"
authors = [
  { name = "Saverio Iacoponi", email = "saverio.iacoponi@ku.ac.ae" }
]
requires-python = ">=3.8"
dependencies = [
  "numpy",
  "scipy",
  "pandas",
  "pyqtgraph>=0.13",
  "PyQt5",
  "openpyxl",
  "imageio[ffmpeg]>=2.31"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
"SwarmSwIM" = ["*.xml"]

[project.scripts]
SwarmSwIM = "SwarmSwIM.utility.cli:main"